# Generated by Django 5.0.4 on 2026-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_upcoming',
            field=models.BooleanField(default=False, help_text='Inaonyesha kwenye sehemu ya "Inakuja Hivi Karibuni"', verbose_name='Upcoming Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_label',
            field=models.CharField(blank=True, help_text='e.g. "Flash Sale", "Wiki Hii Tu", "Punguzo la 20%"', max_length=60, verbose_name='Offer Label'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_label_sw',
            field=models.CharField(blank=True, max_length=60, verbose_name='Offer Label (Swahili)'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acha wazi kama hakuna ofa', max_digits=12, null=True, verbose_name='Offer Price (TSH)'),
        ),
        migrations.AddField(
            model_name='product',
            name='upcoming_date',
            field=models.DateField(blank=True, help_text='Tarehe inayotarajiwa kufika (optional)', null=True, verbose_name='Expected Arrival Date'),
        ),
    ]
