# Generated by Django 5.0.4 on 2026-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('discount_percent', models.PositiveIntegerField(default=10, verbose_name='Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Balance Due on Delivery (TSH)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Fee (TSH)'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Deposit Paid (TSH)'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (TSH)'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Promo Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Hakulipa'), ('deposit_paid', 'Amana imelipwa (70%)'), ('paid', 'Amelipa')], default='unpaid', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal (TSH)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('cod', 'Lipa ukipokea mzigo (Cash on Delivery)'), ('deposit', 'Amana 70% — Lipa 30% siku ya kupokea')], default='cod', max_length=50, verbose_name='Payment Method'),
        ),
    ]
